# QuantumSentinel-Nexus Multi-Platform Bug Bounty Configuration
# Comprehensive configuration for all major bug bounty platforms

# =============================================================================
# HACKERONE CONFIGURATION
# =============================================================================
hackerone:
  platform_info:
    name: "HackerOne"
    type: "comprehensive_bounty"
    base_url: "https://hackerone.com"
    api_endpoint: "https://api.hackerone.com/v1"
    programs_url: "https://hackerone.com/opportunities/all"

  program_categories:
    technology:
      - "Web Applications"
      - "Mobile Applications"
      - "APIs"
      - "Cloud Infrastructure"
      - "IoT Devices"
      - "Blockchain/Crypto"

    industry:
      - "Financial Services"
      - "Government"
      - "E-commerce"
      - "Social Media"
      - "SaaS"
      - "Gaming"

  bounty_ranges:
    critical: "$5000-$50000+"
    high: "$1000-$10000"
    medium: "$500-$5000"
    low: "$100-$1000"

  submission_requirements:
    - "Clear vulnerability description"
    - "Step-by-step reproduction"
    - "Impact assessment"
    - "Proof of concept"
    - "Affected endpoints/components"

  popular_programs:
    - "Shopify"
    - "GitLab"
    - "Uber"
    - "Yahoo"
    - "Slack"
    - "Dropbox"
    - "Spotify"
    - "Twitter"

# =============================================================================
# BUGCROWD CONFIGURATION
# =============================================================================
bugcrowd:
  platform_info:
    name: "Bugcrowd"
    type: "crowd_security"
    base_url: "https://bugcrowd.com"
    api_endpoint: "https://api.bugcrowd.com/v2"
    programs_url: "https://bugcrowd.com/engagements"

  program_categories:
    engagement_types:
      - "Bug Bounty"
      - "VDP (Vulnerability Disclosure)"
      - "Penetration Testing"
      - "Attack Surface Management"

    target_types:
      - "Web Applications"
      - "Mobile Apps (Android/iOS)"
      - "APIs and Web Services"
      - "Network Infrastructure"
      - "Hardware/IoT"

  bounty_ranges:
    critical: "$2000-$25000+"
    high: "$500-$5000"
    medium: "$250-$2000"
    low: "$50-$500"

  submission_requirements:
    - "Vulnerability summary"
    - "Detailed description"
    - "Steps to reproduce"
    - "Impact analysis"
    - "Remediation suggestions"

  popular_programs:
    - "Tesla"
    - "MasterCard"
    - "Western Union"
    - "Fitbit"
    - "Atlassian"

# =============================================================================
# INTIGRITI CONFIGURATION
# =============================================================================
intigriti:
  platform_info:
    name: "Intigriti"
    type: "european_focused"
    base_url: "https://intigriti.com"
    api_endpoint: "https://api.intigriti.com/external"
    programs_url: "https://intigriti.com/researchers/bug-bounty-programs"

  program_categories:
    focus_areas:
      - "European Companies"
      - "GDPR Compliance"
      - "Web Applications"
      - "Mobile Security"
      - "API Security"

    industries:
      - "FinTech"
      - "Healthcare"
      - "Government"
      - "E-commerce"
      - "Enterprise Software"

  bounty_ranges:
    critical: "$1000-$15000+"
    high: "$500-$5000"
    medium: "$250-$2000"
    low: "$50-$500"

  submission_requirements:
    - "Executive summary"
    - "Technical details"
    - "Proof of concept"
    - "Business impact"
    - "GDPR considerations (if applicable)"

  compliance_focus:
    - "GDPR compliance testing"
    - "Privacy impact assessment"
    - "Data protection validation"
    - "EU regulatory compliance"

# =============================================================================
# GOOGLE VRP CONFIGURATION
# =============================================================================
google_vrp:
  platform_info:
    name: "Google VRP"
    type: "vendor_program"
    base_url: "https://bughunters.google.com"
    submission_url: "https://bughunters.google.com/report"

  scope_categories:
    google_services:
      - "Google Search"
      - "Gmail"
      - "Google Drive"
      - "YouTube"
      - "Google Cloud Platform"
      - "Android"
      - "Chrome Browser"
      - "Google Pay"

    reward_tiers:
      baseline: "$100-$1337"
      high_quality: "$3133.7-$31337"
      exceptional: "$31337+"

  focus_areas:
    - "Authentication bypasses"
    - "Authorization flaws"
    - "Data exposure"
    - "Remote code execution"
    - "Cross-site scripting"
    - "SQL injection"
    - "CSRF vulnerabilities"

  submission_requirements:
    - "Affected product/service"
    - "Vulnerability type"
    - "Attack scenario"
    - "Technical details"
    - "Proof of concept"

# =============================================================================
# APPLE SECURITY CONFIGURATION
# =============================================================================
apple_security:
  platform_info:
    name: "Apple Security Bounty"
    type: "vendor_program"
    base_url: "https://security.apple.com"
    invitation_only: true

  scope_categories:
    platforms:
      - "iOS"
      - "macOS"
      - "watchOS"
      - "tvOS"
      - "iPadOS"
      - "iCloud"
      - "Apple Services"

    vulnerability_types:
      - "Network attacks without user interaction"
      - "Lock screen bypass"
      - "Unauthorized access to sensitive data"
      - "Code execution vulnerabilities"
      - "Privilege escalation"

  bounty_ranges:
    exceptional: "$1000000+"  # Zero-click kernel code execution
    critical: "$100000-$1000000"
    high: "$25000-$100000"
    medium: "$5000-$25000"

  requirements:
    - "Invitation-only program"
    - "Detailed proof of concept"
    - "Clear demonstration"
    - "Original research"

# =============================================================================
# SAMSUNG MOBILE SECURITY CONFIGURATION
# =============================================================================
samsung_mobile:
  platform_info:
    name: "Samsung Mobile Security"
    type: "mobile_focused"
    base_url: "https://security.samsungmobile.com"

  scope_categories:
    devices:
      - "Galaxy Smartphones"
      - "Galaxy Tablets"
      - "Galaxy Watches"
      - "Galaxy Buds"
      - "Samsung Knox"

    focus_areas:
      - "Android security"
      - "Knox security platform"
      - "Secure folder"
      - "Samsung Pay"
      - "Bixby"
      - "Samsung Cloud"

  bounty_ranges:
    critical: "$5000-$200000"
    high: "$1000-$20000"
    medium: "$500-$5000"
    low: "$100-$1000"

  requirements:
    - "Reproducible vulnerabilities"
    - "Latest device firmware"
    - "Clear impact assessment"
    - "Responsible disclosure"

# =============================================================================
# MICROSOFT MSRC CONFIGURATION
# =============================================================================
microsoft_msrc:
  platform_info:
    name: "Microsoft Security Response Center"
    type: "vendor_program"
    base_url: "https://www.microsoft.com/en-us/msrc"
    bounty_url: "https://www.microsoft.com/en-us/msrc/bounty"

  scope_categories:
    products:
      - "Windows"
      - "Microsoft 365"
      - "Azure"
      - "Office"
      - "Edge Browser"
      - "Visual Studio"
      - "Xbox"
      - "Surface"

    cloud_services:
      - "Azure Active Directory"
      - "Microsoft Graph"
      - "Exchange Online"
      - "SharePoint Online"
      - "Teams"

  bounty_ranges:
    hyper_v_rce: "$250000"
    azure_rce: "$40000"
    windows_rce: "$30000"
    identity_bypass: "$26000"
    standard_vulnerabilities: "$500-$15000"

  focus_areas:
    - "Remote code execution"
    - "Privilege escalation"
    - "Authentication bypass"
    - "Information disclosure"
    - "Security feature bypass"

# =============================================================================
# COMMON VULNERABILITY TYPES ACROSS PLATFORMS
# =============================================================================
common_vulnerability_types:
  web_application:
    - "SQL Injection"
    - "Cross-Site Scripting (XSS)"
    - "Cross-Site Request Forgery (CSRF)"
    - "Server-Side Request Forgery (SSRF)"
    - "Authentication Bypass"
    - "Authorization Flaws"
    - "File Upload Vulnerabilities"
    - "Directory Traversal"
    - "Remote Code Execution"
    - "Business Logic Flaws"

  mobile_application:
    - "Insecure Data Storage"
    - "Weak Cryptography"
    - "Insecure Authentication"
    - "Code Injection"
    - "Reverse Engineering"
    - "Runtime Application Self-Protection Bypass"
    - "Certificate Pinning Bypass"
    - "Deep Link Abuse"

  api_security:
    - "Broken Object Level Authorization"
    - "Broken User Authentication"
    - "Excessive Data Exposure"
    - "Lack of Resources & Rate Limiting"
    - "Broken Function Level Authorization"
    - "Mass Assignment"
    - "Security Misconfiguration"
    - "Injection"

  infrastructure:
    - "Server Misconfigurations"
    - "Weak Cryptographic Implementations"
    - "Information Disclosure"
    - "Denial of Service"
    - "Cloud Misconfigurations"
    - "Container Escape"
    - "Privilege Escalation"

# =============================================================================
# SCAN PROFILES BY PLATFORM
# =============================================================================
scan_profiles:
  hackerone_comprehensive:
    scan_depth: "comprehensive"
    timeout_minutes: 180
    focus_areas:
      - "web_application_security"
      - "api_security_testing"
      - "business_logic_testing"
      - "authentication_testing"
      - "authorization_testing"

  bugcrowd_standard:
    scan_depth: "standard"
    timeout_minutes: 120
    focus_areas:
      - "vulnerability_discovery"
      - "impact_assessment"
      - "proof_of_concept"
      - "remediation_guidance"

  google_vrp_focused:
    scan_depth: "comprehensive"
    timeout_minutes: 240
    focus_areas:
      - "google_services_testing"
      - "oauth_security"
      - "api_security"
      - "mobile_app_testing"

  apple_deep_security:
    scan_depth: "extreme"
    timeout_minutes: 300
    focus_areas:
      - "ios_security_testing"
      - "macos_security_testing"
      - "kernel_vulnerability_research"
      - "sandbox_escape_testing"

  microsoft_azure_focused:
    scan_depth: "comprehensive"
    timeout_minutes: 200
    focus_areas:
      - "azure_security_testing"
      - "active_directory_testing"
      - "office365_security"
      - "windows_security"

# =============================================================================
# EVIDENCE COLLECTION BY PLATFORM
# =============================================================================
evidence_requirements:
  hackerone:
    required_evidence:
      - "screenshots"
      - "http_requests_responses"
      - "proof_of_concept_code"
      - "video_demonstration"

  bugcrowd:
    required_evidence:
      - "step_by_step_reproduction"
      - "impact_demonstration"
      - "screenshots"
      - "network_traffic"

  google_vrp:
    required_evidence:
      - "detailed_technical_analysis"
      - "proof_of_concept"
      - "affected_urls_endpoints"
      - "impact_assessment"

  apple_security:
    required_evidence:
      - "comprehensive_poc"
      - "detailed_writeup"
      - "demonstration_video"
      - "technical_analysis"

# =============================================================================
# REPORTING TEMPLATES BY PLATFORM
# =============================================================================
reporting_templates:
  hackerone_format:
    sections:
      - "Summary"
      - "Description"
      - "Steps to Reproduce"
      - "Impact"
      - "Proof of Concept"
      - "Remediation"

  bugcrowd_format:
    sections:
      - "Vulnerability Summary"
      - "Technical Details"
      - "Reproduction Steps"
      - "Business Impact"
      - "Remediation Advice"

  google_vrp_format:
    sections:
      - "Affected Product"
      - "Vulnerability Type"
      - "Attack Scenario"
      - "Technical Details"
      - "Proof of Concept"

  vendor_program_format:
    sections:
      - "Executive Summary"
      - "Technical Analysis"
      - "Proof of Concept"
      - "Impact Assessment"
      - "Remediation Guidance"